### PR TITLE
add comnet support

### PR DESCRIPTION
**Pull request by Thoralf-M**

### CODE REVIEW

**Comment by allemanfredi** [comment]
Hello @Thoralf-M!

Just tried your PR and the name used is too long and causes a text overflow in the network selection. As soon as I fix this little bug and I will merge your PR.

In case you want to do it, I would be happy!

thank you very much for your contribution!

**Comment by Thoralf-M** [comment]
We can also make the name shorter, I just followed the format you used for the other addresses, so maybe `comnet.thetangle.org` or just `comnet.thetangle`?

**Comment by allemanfredi** [comment]
`comnet.thetangle.org` it's ok!!

**Comment by allemanfredi** [comment]
I was wondering just one thing, why did you use 10 as a difficulty instead of 9 (just to know)? I knew that the default was 9 for testnets.

**Comment by Thoralf-M** [comment]
Comnet MWM is 10, it's not the devnet

**Comment by allemanfredi** [comment]
merged! thanks @Thoralf-M

**Pull request merged**
